//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbleToTrack.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbleToTrack.Resources.AppResources.es", typeof(AppResources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string ForgotPassword_Button_Send {
            get {
                return ResourceManager.GetString("ForgotPassword.Button.Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese su dirección de correo. Recibirá un enlace para crear una nueva contraseña..
        /// </summary>
        public static string ForgotPassword_TextBlock_Description {
            get {
                return ResourceManager.GetString("ForgotPassword.TextBlock.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar contraseña.
        /// </summary>
        public static string ForgotPassword_TextBlock_Title {
            get {
                return ResourceManager.GetString("ForgotPassword.TextBlock.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string Login_Button_SignIn {
            get {
                return ResourceManager.GetString("Login.Button.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Regístrese ahora!.
        /// </summary>
        public static string Login_Button_SignUpNow {
            get {
                return ResourceManager.GetString("Login.Button.SignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuérdame.
        /// </summary>
        public static string Login_CheckBox_RememberMe {
            get {
                return ResourceManager.GetString("Login.CheckBox.RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique su dirección de correo, o no podrá iniciar sesión.
        /// </summary>
        public static string Login_Error_EmailNotVerified {
            get {
                return ResourceManager.GetString("Login.Error.EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o contraseña incorrectos.
        /// </summary>
        public static string Login_Error_InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("Login.Error.InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidó su contraseña?.
        /// </summary>
        public static string Login_Hyperlink_ForgotPassword {
            get {
                return ResourceManager.GetString("Login.Hyperlink.ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Su correo no está verificado!.
        /// </summary>
        public static string Login_MessageBox_Title_EmailNotVerified {
            get {
                return ResourceManager.GetString("Login.MessageBox.Title.EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al iniciar sesión.
        /// </summary>
        public static string Login_MessageBox_Title_LoginError {
            get {
                return ResourceManager.GetString("Login.MessageBox.Title.LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGUIMIENTO DE HORAS LABORALES.
        /// </summary>
        public static string Login_TextBlock_AppDescription {
            get {
                return ResourceManager.GetString("Login.TextBlock.AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo-e.
        /// </summary>
        public static string Login_TextBlock_Email {
            get {
                return ResourceManager.GetString("Login.TextBlock.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tiene cuenta?.
        /// </summary>
        public static string Login_TextBlock_NoAccount {
            get {
                return ResourceManager.GetString("Login.TextBlock.NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Login_TextBlock_Password {
            get {
                return ResourceManager.GetString("Login.TextBlock.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor inicie sesión.
        /// </summary>
        public static string Login_TextBlock_PleaseSignIn {
            get {
                return ResourceManager.GetString("Login.TextBlock.PleaseSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a AbleToTrack.
        /// </summary>
        public static string Login_TextBlock_Welcome {
            get {
                return ResourceManager.GetString("Login.TextBlock.Welcome", resourceCulture);
            }
        }
    }
}
